"""
De-Droid Model Store — Loads and caches the ML model artifact and precomputed prediction cache.

This module provides the ModelStore class which is responsible for reading the
``safety_predictions.json`` cache file and the ``safety_baseline.joblib`` model
artifact from disk at startup, then serving fast in-memory lookups to the rest of
the application.

Usage::

    store = ModelStore(
        model_dir=Path("model-api/model-api/models"),
        predictions_path=Path("model-api/model-api/models/safety_predictions.json"),
    )
    store.load()

    pred = store.get_prediction("com.example.app")   # dict | None
    print(store.version)                              # e.g. "2.1.0"
    print(store.predictions_count)                    # e.g. 42817
    print(store.is_model_loaded)                      # True / False
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import joblib


class ModelStore:
    """Loads and caches the ML model artifact and precomputed prediction cache.

    The store is designed to be created once during application startup and then
    accessed read-only from every request handler.  All heavy I/O is deferred to
    :meth:`load` so the instance can be constructed synchronously during the
    module-level global state initialisation phase.

    Args:
        model_dir: Directory that contains ``safety_baseline.joblib``.
        predictions_path: Full path to ``safety_predictions.json``.

    Attributes:
        _model_dir: Resolved directory containing the joblib artifact.
        _predictions_path: Resolved path to the predictions JSON file.
        _predictions: In-memory dict mapping package IDs to prediction payloads.
        _model_artifact: The loaded joblib object, or ``None`` if unavailable.
        _version: Model version string extracted from the predictions file.
    """

    def __init__(self, model_dir: Path, predictions_path: Path) -> None:
        self._model_dir: Path = model_dir
        self._predictions_path: Path = predictions_path
        self._predictions: dict[str, Any] = {}
        self._model_artifact: Any | None = None
        self._version: str = "unknown"

    # ──────────────────────────────────────────────────────────────────────────
    # Properties
    # ──────────────────────────────────────────────────────────────────────────

    @property
    def version(self) -> str:
        """The model version string extracted from ``safety_predictions.json``.

        Returns ``"unknown"`` when the predictions file has not been loaded yet
        or does not contain a ``modelVersion`` key.
        """
        return self._version

    @property
    def is_model_loaded(self) -> bool:
        """``True`` when the joblib model artifact is held in memory.

        The artifact is loaded lazily by :meth:`load` and stays ``None`` when
        the file is absent or could not be deserialized.
        """
        return self._model_artifact is not None

    @property
    def predictions_count(self) -> int:
        """Number of package entries in the in-memory predictions cache."""
        return len(self._predictions)

    # ──────────────────────────────────────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────────────────────────────────────

    def load(self) -> None:
        """Load the model artifact and the predictions JSON from disk.

        This method is **idempotent**: calling it multiple times is safe, though
        it will re-read from disk on each call.  Prefer :meth:`reload` when you
        explicitly want to discard cached state before re-loading.

        Both loading steps are independent — a failure in one does not prevent
        the other from succeeding.
        """
        self._load_predictions()
        self._load_model()

    def reload(self) -> None:
        """Discard all cached state and force a fresh load from disk.

        Useful for hot-reload scenarios or when the predictions file has been
        regenerated by the training pipeline without restarting the server.
        """
        self._predictions = {}
        self._model_artifact = None
        self._version = "unknown"
        self.load()

    def get_prediction(self, package_id: str) -> dict[str, Any] | None:
        """Return the cached prediction payload for *package_id*, or ``None``.

        The returned dict typically contains keys such as ``"label"``,
        ``"confidence"``, ``"top_factors"``, and ``"safety_gate"``.  Callers
        should not mutate the returned mapping.

        Args:
            package_id: Exact Android package identifier to look up.

        Returns:
            The prediction payload dict, or ``None`` when the package is absent
            from the cache.
        """
        return self._predictions.get(package_id)

    def get_all_predictions(self) -> dict[str, Any]:
        """Return a read-only view of the full in-memory predictions cache.

        This is intended for bulk operations such as statistics calculation and
        search.  Callers **must not** mutate the returned mapping.

        Returns:
            The complete ``{package_id: prediction_dict}`` mapping.
        """
        return self._predictions

    # ──────────────────────────────────────────────────────────────────────────
    # Private helpers
    # ──────────────────────────────────────────────────────────────────────────

    def _load_predictions(self) -> None:
        """Read ``safety_predictions.json`` into ``_predictions`` and set ``_version``.

        Silently skips loading when the file does not exist.  Any JSON parse
        error is surfaced as a printed warning rather than a raised exception so
        the API can still start up in a degraded state.
        """
        if not self._predictions_path.exists():
            print(f"[ModelStore] No predictions file at {self._predictions_path}")
            return

        try:
            with self._predictions_path.open("r", encoding="utf-8") as fh:
                data = json.load(fh)
        except Exception as exc:
            print(f"[ModelStore] Could not parse predictions file: {exc}")
            return

        self._predictions = data.get("predictions", {})
        self._version = data.get("modelVersion", "unknown")
        print(
            f"[ModelStore] Loaded {len(self._predictions)} predictions "
            f"(v={self._version})"
        )

    def _load_model(self) -> None:
        """Deserialize ``safety_baseline.joblib`` from ``_model_dir``.

        Silently skips loading when the file does not exist.  Joblib
        deserialization errors are caught and printed so the API can continue
        operating in predictions-only mode.
        """
        model_path = self._model_dir / "safety_baseline.joblib"
        if not model_path.exists():
            print(f"[ModelStore] No model file at {model_path}")
            return

        try:
            self._model_artifact = joblib.load(model_path)
            print(f"[ModelStore] Loaded model artifact from {model_path}")
        except Exception as exc:
            print(f"[ModelStore] Could not load model: {exc}")
